version: 2.1

orbs:
  win: circleci/windows@1.0.0

jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.0
    environment:
      DOTNET_ROLL_FORWARD_ON_NO_CANDIDATE_FX: 2
    steps:
      - checkout
      - run:
          name: "Install project dependencies"
          command: dotnet.exe restore
      - run:
          name: "Run Build step"
          command: dotnet.exe publish -c Release -r win10-x64
